# Site settings
course_name: Building Reliable And Secure Systems
course_description: "This course will explore modern techniques for building software systems that are reliable, resilient, and secure. The Rust programming language is covered, along with software build systems and the DevOps and methodologies."
course_semester: "Spring 2025"

baseurl: "/sp2025" # the subpath of your site, e.g. /blog/
url: "http://cosc-69-brass.github.io/" # the base hostname & protocol for your site

schoolname: "Dartmouth College"
schoolurl: "https://dartmouth.edu"
twitter_username: "drcybersecurity"

address: |
    Dartmouth College
    Hanover
    New Hampshire

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
